---
# Purpose: create the instance(s) defined in molecule.yml
# Molecule calls this playbook with `molecule create`.
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Create molecule instance(s)
      molecule_podman:
        name: "{{ item.name }}"
        image: "{{ item.image }}"
        state: started
        privileged: "{{ item.privileged | default(false) }}"
        volumes: "{{ item.volumes | default([]) }}"
        command: "{{ item.command | default('') }}"
        pre_build_image: "{{ item.pre_build_image | default(false) }}"
      loop: "{{ molecule_yml.platforms }}"
      register: molecule_instance
      async: 7200
      poll: 0

    - name: Wait for instance(s) creation to complete
      async_status:
        jid: "{{ item.ansible_job_id }}"
      loop: "{{ molecule_instance.results }}"
      register: molecule_instance_result
      until: molecule_instance_result.finished
      retries: 300